### ISSUE TITLE
Implemented protocol revision 

### ISSUE THREAD

**Issue by cpu** [Inria-Prosecco/acme-model#1]
Section 4.2 begins

> In this paper we focus on draft-1 of the IETF specification for the ACME protocol,
> which is as of October 2016 also the draft specification deployed in official
> Let’s Encrypt client and server implementations

In October 2016 the Let's Encrypt implementation is more accurately characterized as being somewhere between draft-02 and draft-03 (see [acme-divergences.md](https://github.com/letsencrypt/boulder/blob/master/docs/acme-divergences.md))

**Comment by prosecco** [comment]
Thanks, we’ll fix.

**Comment by cpu** [comment]
Merci!

**Comment by nadimkobeissi** [comment]
Thanks, I'll shortly push a correction.
