### ISSUE TITLE
Let's Encrypt/Cloudflare Errata

### ISSUE THREAD

**Issue by cpu** [Inria-Prosecco/acme-model#2]
I believe page 6, footnote #3 isn't right:

> CloudFlare incidentally also operates Let’s Encrypt’s infrastructure, rendering it
> a centralized point of failure for ACME and ad-hoc CAs alike. While ACME is
> a centralization-agnostic protocol, Let’s Encrypt operates with a fully centralized
> infrastructure.

We don't use Cloudflare for any of our infrastructure to the best of my knowledge. Perhaps this is a historic artifact? What led you to this conclusion? 

Similarly. why would CloudFlare be a "centralized point of failure" for "ACME and ad-hoc CAs alike". Even if Let's Encrypt were using CloudFlare there isn't any part of ACME that would force other implementors to do the same.

**Comment by prosecco** [comment]
Did we misunderstand that LE was using CF as a CDN?

**Comment by cpu** [comment]
@prosecco Yes, I confirmed with our ops team. We've always used Akamai as our CDN. There's an argument to be made that Akamai is a single point of failure for Let's Encrypt but other ACME implementors or ad-hoc CAs wouldn't be required to make that choice.

**Comment by prosecco** [comment]
Akamai becomes a point of failure in two ways.
It can get certificates for any domain (including LE) from any traditional CA.
It can intercept ACME requests to LE (although this shouldn’t give it too much power, if ACME does its job.)

**Comment by cpu** [comment]
Yup! No criticisms of that line of reasoning. I just want to make sure that its clear that's a result of the choices made by Let's Encrypt and doesn't affect other ACME implementors unless they make the same choice of their own volition :-)

**Comment by nadimkobeissi** [comment]
I'm noting this conversation and will soon push an update to the research report with the necessary fixes.
